//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors_Publishers
    {
        public int Publisher_ID { get; set; }
        public int Author_ID { get; set; }
        public System.DateTime Apply_Date { get; set; }
        public Nullable<System.DateTime> Severance_Date { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual Authors Authors { get; set; }
    }
}
