//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookStoreEntities : DbContext
    {
        public BookStoreEntities()
            : base("name=BookStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Authors_Publishers> Authors_Publishers { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Books_Orders> Books_Orders { get; set; }
        public virtual DbSet<CustomerLevel> CustomerLevels { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Warehouse_Books> Warehouse_Books { get; set; }
        public virtual DbSet<v_AllProducts> v_AllProducts { get; set; }
        public virtual DbSet<v_AllSumOrderByCus_ID> v_AllSumOrderByCus_ID { get; set; }
        public virtual DbSet<v_AllSumOrderByOrder_ID> v_AllSumOrderByOrder_ID { get; set; }
        public virtual DbSet<v_Top3Authors> v_Top3Authors { get; set; }
        public virtual DbSet<v_Top5Books> v_Top5Books { get; set; }
        public virtual DbSet<v_TopAuthors> v_TopAuthors { get; set; }
    
        [DbFunction("BookStoreEntities", "Fn_GetOrder_ByCustomer")]
        public virtual IQueryable<Fn_GetOrder_ByCustomer_Result> Fn_GetOrder_ByCustomer(Nullable<int> cUSTOMER_ID)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetOrder_ByCustomer_Result>("[BookStoreEntities].[Fn_GetOrder_ByCustomer](@CUSTOMER_ID)", cUSTOMER_IDParameter);
        }
    
        [DbFunction("BookStoreEntities", "Fn_GetRevenue_ByYearMonth")]
        public virtual IQueryable<Fn_GetRevenue_ByYearMonth_Result> Fn_GetRevenue_ByYearMonth(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetRevenue_ByYearMonth_Result>("[BookStoreEntities].[Fn_GetRevenue_ByYearMonth](@Month, @Year)", monthParameter, yearParameter);
        }
    
        [DbFunction("BookStoreEntities", "Fn_GetTop3_BestAuthorOfTheYear")]
        public virtual IQueryable<Fn_GetTop3_BestAuthorOfTheYear_Result> Fn_GetTop3_BestAuthorOfTheYear(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetTop3_BestAuthorOfTheYear_Result>("[BookStoreEntities].[Fn_GetTop3_BestAuthorOfTheYear](@Year)", yearParameter);
        }
    
        [DbFunction("BookStoreEntities", "Fn_GetTop5BestSellerOfTheYear")]
        public virtual IQueryable<Fn_GetTop5BestSellerOfTheYear_Result> Fn_GetTop5BestSellerOfTheYear(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetTop5BestSellerOfTheYear_Result>("[BookStoreEntities].[Fn_GetTop5BestSellerOfTheYear](@Year)", yearParameter);
        }
    
        [DbFunction("BookStoreEntities", "Fn_GetUser")]
        public virtual IQueryable<Fn_GetUser_Result> Fn_GetUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetUser_Result>("[BookStoreEntities].[Fn_GetUser](@Username, @Password)", usernameParameter, passwordParameter);
        }
    
        public virtual int add_customer_level(Nullable<int> level, string desc, Nullable<decimal> discountRate)
        {
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var discountRateParameter = discountRate.HasValue ?
                new ObjectParameter("discountRate", discountRate) :
                new ObjectParameter("discountRate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_customer_level", levelParameter, descParameter, discountRateParameter);
        }
    
        public virtual int Pr_Add_Author_Publisher(Nullable<int> publisher_id, Nullable<int> author_id, Nullable<System.DateTime> apply_date, Nullable<System.DateTime> severance_date)
        {
            var publisher_idParameter = publisher_id.HasValue ?
                new ObjectParameter("publisher_id", publisher_id) :
                new ObjectParameter("publisher_id", typeof(int));
    
            var author_idParameter = author_id.HasValue ?
                new ObjectParameter("author_id", author_id) :
                new ObjectParameter("author_id", typeof(int));
    
            var apply_dateParameter = apply_date.HasValue ?
                new ObjectParameter("apply_date", apply_date) :
                new ObjectParameter("apply_date", typeof(System.DateTime));
    
            var severance_dateParameter = severance_date.HasValue ?
                new ObjectParameter("severance_date", severance_date) :
                new ObjectParameter("severance_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Add_Author_Publisher", publisher_idParameter, author_idParameter, apply_dateParameter, severance_dateParameter);
        }
    
        public virtual int Pr_Add_Books_Genres(Nullable<int> genre_ID, Nullable<int> book_ID)
        {
            var genre_IDParameter = genre_ID.HasValue ?
                new ObjectParameter("genre_ID", genre_ID) :
                new ObjectParameter("genre_ID", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Add_Books_Genres", genre_IDParameter, book_IDParameter);
        }
    
        public virtual int Pr_Add_books_orders(Nullable<int> order_ID, Nullable<int> book_ID, Nullable<int> amount)
        {
            var order_IDParameter = order_ID.HasValue ?
                new ObjectParameter("order_ID", order_ID) :
                new ObjectParameter("order_ID", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Add_books_orders", order_IDParameter, book_IDParameter, amountParameter);
        }
    
        public virtual int Pr_add_customer_level(Nullable<int> level, string desc, Nullable<int> discountRate)
        {
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var discountRateParameter = discountRate.HasValue ?
                new ObjectParameter("discountRate", discountRate) :
                new ObjectParameter("discountRate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_add_customer_level", levelParameter, descParameter, discountRateParameter);
        }
    
        public virtual int Pr_Add_WareHouse(Nullable<int> seri, Nullable<System.DateTime> date)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Add_WareHouse", seriParameter, dateParameter);
        }
    
        public virtual int PR_add_warehouse_book(Nullable<int> seri, Nullable<int> book_ID, Nullable<int> quantity)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_add_warehouse_book", seriParameter, book_IDParameter, quantityParameter);
        }
    
        public virtual int Pr_AddAuthor(string name, Nullable<System.DateTime> date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddAuthor", nameParameter, dateParameter);
        }
    
        public virtual int Pr_AddBook(string name, Nullable<double> price, string author_Name, string publisher_Name, Nullable<System.DateTime> release_date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var author_NameParameter = author_Name != null ?
                new ObjectParameter("Author_Name", author_Name) :
                new ObjectParameter("Author_Name", typeof(string));
    
            var publisher_NameParameter = publisher_Name != null ?
                new ObjectParameter("Publisher_Name", publisher_Name) :
                new ObjectParameter("Publisher_Name", typeof(string));
    
            var release_dateParameter = release_date.HasValue ?
                new ObjectParameter("Release_date", release_date) :
                new ObjectParameter("Release_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddBook", nameParameter, priceParameter, author_NameParameter, publisher_NameParameter, release_dateParameter);
        }
    
        public virtual int Pr_AddCustomer(string name, string address, string country, string phone, string email, string username, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddCustomer", nameParameter, addressParameter, countryParameter, phoneParameter, emailParameter, usernameParameter, passwordParameter);
        }
    
        public virtual int Pr_AddGenre(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddGenre", nameParameter);
        }
    
        public virtual int Pr_AddOrder(Nullable<int> customerID, Nullable<System.DateTime> date, Nullable<int> shippingMethodID, string paymentMethod, Nullable<decimal> discountShip)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("customerID", customerID) :
                new ObjectParameter("customerID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var shippingMethodIDParameter = shippingMethodID.HasValue ?
                new ObjectParameter("shippingMethodID", shippingMethodID) :
                new ObjectParameter("shippingMethodID", typeof(int));
    
            var paymentMethodParameter = paymentMethod != null ?
                new ObjectParameter("paymentMethod", paymentMethod) :
                new ObjectParameter("paymentMethod", typeof(string));
    
            var discountShipParameter = discountShip.HasValue ?
                new ObjectParameter("discountShip", discountShip) :
                new ObjectParameter("discountShip", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddOrder", customerIDParameter, dateParameter, shippingMethodIDParameter, paymentMethodParameter, discountShipParameter);
        }
    
        public virtual int Pr_AddPublisher(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddPublisher", nameParameter);
        }
    
        public virtual int Pr_AddShippingMethod(string method, Nullable<decimal> cost)
        {
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_AddShippingMethod", methodParameter, costParameter);
        }
    
        public virtual int Pr_Delete_Author_Publisher(Nullable<int> publisher_ID, Nullable<int> author_ID)
        {
            var publisher_IDParameter = publisher_ID.HasValue ?
                new ObjectParameter("publisher_ID", publisher_ID) :
                new ObjectParameter("publisher_ID", typeof(int));
    
            var author_IDParameter = author_ID.HasValue ?
                new ObjectParameter("author_ID", author_ID) :
                new ObjectParameter("author_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Delete_Author_Publisher", publisher_IDParameter, author_IDParameter);
        }
    
        public virtual int Pr_Delete_Books_Genres(Nullable<int> genre_ID, Nullable<int> book_ID)
        {
            var genre_IDParameter = genre_ID.HasValue ?
                new ObjectParameter("genre_ID", genre_ID) :
                new ObjectParameter("genre_ID", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Delete_Books_Genres", genre_IDParameter, book_IDParameter);
        }
    
        public virtual int Pr_Delete_books_order(Nullable<int> order_ID, Nullable<int> book_ID)
        {
            var order_IDParameter = order_ID.HasValue ?
                new ObjectParameter("order_ID", order_ID) :
                new ObjectParameter("order_ID", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Delete_books_order", order_IDParameter, book_IDParameter);
        }
    
        public virtual int Pr_delete_customer_level(Nullable<int> level)
        {
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_delete_customer_level", levelParameter);
        }
    
        public virtual int Pr_Delete_publisher(Nullable<int> publisher_id)
        {
            var publisher_idParameter = publisher_id.HasValue ?
                new ObjectParameter("publisher_id", publisher_id) :
                new ObjectParameter("publisher_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Delete_publisher", publisher_idParameter);
        }
    
        public virtual int Pr_Delete_Warehouse(Nullable<int> seri)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Delete_Warehouse", seriParameter);
        }
    
        public virtual int Pr_delete_warehouse_book(Nullable<int> seri, Nullable<int> book_ID)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_delete_warehouse_book", seriParameter, book_IDParameter);
        }
    
        public virtual int PR_DeleteAuthor(Nullable<int> author_id)
        {
            var author_idParameter = author_id.HasValue ?
                new ObjectParameter("author_id", author_id) :
                new ObjectParameter("author_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_DeleteAuthor", author_idParameter);
        }
    
        public virtual int Pr_DeleteBook(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteBook", iDParameter);
        }
    
        public virtual int Pr_DeleteCustomer(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteCustomer", iDParameter);
        }
    
        public virtual int Pr_DeleteGenre(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteGenre", idParameter);
        }
    
        public virtual int Pr_DeleteOrder(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("orderID", orderID) :
                new ObjectParameter("orderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteOrder", orderIDParameter);
        }
    
        public virtual int Pr_DeleteShipping(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteShipping", iDParameter);
        }
    
        public virtual int Pr_SetCustomerLevel(Nullable<int> customer_ID)
        {
            var customer_IDParameter = customer_ID.HasValue ?
                new ObjectParameter("customer_ID", customer_ID) :
                new ObjectParameter("customer_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_SetCustomerLevel", customer_IDParameter);
        }
    
        public virtual int Pr_Update_Author_Publisher(Nullable<int> publisher_id, Nullable<int> author_id, Nullable<System.DateTime> apply_date, Nullable<System.DateTime> severance_date)
        {
            var publisher_idParameter = publisher_id.HasValue ?
                new ObjectParameter("publisher_id", publisher_id) :
                new ObjectParameter("publisher_id", typeof(int));
    
            var author_idParameter = author_id.HasValue ?
                new ObjectParameter("author_id", author_id) :
                new ObjectParameter("author_id", typeof(int));
    
            var apply_dateParameter = apply_date.HasValue ?
                new ObjectParameter("apply_date", apply_date) :
                new ObjectParameter("apply_date", typeof(System.DateTime));
    
            var severance_dateParameter = severance_date.HasValue ?
                new ObjectParameter("severance_date", severance_date) :
                new ObjectParameter("severance_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Update_Author_Publisher", publisher_idParameter, author_idParameter, apply_dateParameter, severance_dateParameter);
        }
    
        public virtual int Pr_Update_books_order(Nullable<int> id, Nullable<int> order_id, Nullable<int> book_id, Nullable<int> amount)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var book_idParameter = book_id.HasValue ?
                new ObjectParameter("book_id", book_id) :
                new ObjectParameter("book_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Update_books_order", idParameter, order_idParameter, book_idParameter, amountParameter);
        }
    
        public virtual int Pr_update_customer_level(Nullable<int> level, string desc, Nullable<int> discountRate, Nullable<int> oldLevel)
        {
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var discountRateParameter = discountRate.HasValue ?
                new ObjectParameter("discountRate", discountRate) :
                new ObjectParameter("discountRate", typeof(int));
    
            var oldLevelParameter = oldLevel.HasValue ?
                new ObjectParameter("oldLevel", oldLevel) :
                new ObjectParameter("oldLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_update_customer_level", levelParameter, descParameter, discountRateParameter, oldLevelParameter);
        }
    
        public virtual int Pr_Update_Warehouse(Nullable<int> seri, Nullable<System.DateTime> date)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Update_Warehouse", seriParameter, dateParameter);
        }
    
        public virtual int Pr_update_warehouse_book(Nullable<int> seri, Nullable<int> book_ID, Nullable<int> quantity)
        {
            var seriParameter = seri.HasValue ?
                new ObjectParameter("seri", seri) :
                new ObjectParameter("seri", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_update_warehouse_book", seriParameter, book_IDParameter, quantityParameter);
        }
    
        public virtual int Pr_UpdateAuthor(Nullable<int> iD, string name, Nullable<System.DateTime> date)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateAuthor", iDParameter, nameParameter, dateParameter);
        }
    
        public virtual int Pr_UpdateBook(Nullable<int> iD, string name, Nullable<double> price, string author_Name, string publisher_Name, Nullable<System.DateTime> release_date)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var author_NameParameter = author_Name != null ?
                new ObjectParameter("Author_Name", author_Name) :
                new ObjectParameter("Author_Name", typeof(string));
    
            var publisher_NameParameter = publisher_Name != null ?
                new ObjectParameter("Publisher_Name", publisher_Name) :
                new ObjectParameter("Publisher_Name", typeof(string));
    
            var release_dateParameter = release_date.HasValue ?
                new ObjectParameter("Release_date", release_date) :
                new ObjectParameter("Release_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateBook", iDParameter, nameParameter, priceParameter, author_NameParameter, publisher_NameParameter, release_dateParameter);
        }
    
        public virtual int Pr_UpdateBooksGenres(Nullable<int> genre_ID, Nullable<int> book_ID, Nullable<int> old_genre_ID, Nullable<int> old_book_ID)
        {
            var genre_IDParameter = genre_ID.HasValue ?
                new ObjectParameter("genre_ID", genre_ID) :
                new ObjectParameter("genre_ID", typeof(int));
    
            var book_IDParameter = book_ID.HasValue ?
                new ObjectParameter("book_ID", book_ID) :
                new ObjectParameter("book_ID", typeof(int));
    
            var old_genre_IDParameter = old_genre_ID.HasValue ?
                new ObjectParameter("old_genre_ID", old_genre_ID) :
                new ObjectParameter("old_genre_ID", typeof(int));
    
            var old_book_IDParameter = old_book_ID.HasValue ?
                new ObjectParameter("old_book_ID", old_book_ID) :
                new ObjectParameter("old_book_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateBooksGenres", genre_IDParameter, book_IDParameter, old_genre_IDParameter, old_book_IDParameter);
        }
    
        public virtual int Pr_UpdateCustomer(Nullable<int> id, string name, string address, string country, string phone, string email, string username, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateCustomer", idParameter, nameParameter, addressParameter, countryParameter, phoneParameter, emailParameter, usernameParameter, passwordParameter);
        }
    
        public virtual int Pr_UpdateGenre(Nullable<int> genre_id, string name)
        {
            var genre_idParameter = genre_id.HasValue ?
                new ObjectParameter("genre_id", genre_id) :
                new ObjectParameter("genre_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateGenre", genre_idParameter, nameParameter);
        }
    
        public virtual int Pr_UpdateOrder(Nullable<int> order_id, Nullable<int> customer_id, Nullable<System.DateTime> date, Nullable<int> shipping_id, string payment_method, Nullable<double> discount_ship)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var shipping_idParameter = shipping_id.HasValue ?
                new ObjectParameter("shipping_id", shipping_id) :
                new ObjectParameter("shipping_id", typeof(int));
    
            var payment_methodParameter = payment_method != null ?
                new ObjectParameter("payment_method", payment_method) :
                new ObjectParameter("payment_method", typeof(string));
    
            var discount_shipParameter = discount_ship.HasValue ?
                new ObjectParameter("discount_ship", discount_ship) :
                new ObjectParameter("discount_ship", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateOrder", order_idParameter, customer_idParameter, dateParameter, shipping_idParameter, payment_methodParameter, discount_shipParameter);
        }
    
        public virtual int Pr_UpdatePublisher(Nullable<int> publisher_id, string publisher_name)
        {
            var publisher_idParameter = publisher_id.HasValue ?
                new ObjectParameter("publisher_id", publisher_id) :
                new ObjectParameter("publisher_id", typeof(int));
    
            var publisher_nameParameter = publisher_name != null ?
                new ObjectParameter("publisher_name", publisher_name) :
                new ObjectParameter("publisher_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdatePublisher", publisher_idParameter, publisher_nameParameter);
        }
    
        public virtual int Pr_UpdateShipping(Nullable<int> iD, string method, Nullable<decimal> cost)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateShipping", iDParameter, methodParameter, costParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
