//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Books_Orders = new HashSet<Books_Orders>();
        }
    
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ShippingMethod_ID { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<int> Discount_Ship { get; set; }
        public bool Complete { get; set; }
        public Nullable<double> Total_Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books_Orders> Books_Orders { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
