//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AllSumOrderByOrder_ID
    {
        public int ID { get; set; }
        public Nullable<double> COST { get; set; }
        public int Customer_ID { get; set; }
        public string Name { get; set; }
    }
}
